#!/bin/sh -eu

SNAPDATE='20170922'
SNAPBALL="openssh-SNAP-${SNAPDATE}.tar.gz"

export PT_BUILD_ASSETS="$HOME/Downloads/$SNAPBALL"
export PT_BUILD_SCRIPTS="openssh-snapshot-$SNAPDATE.sh"

test -f "../$PT_BUILD_SCRIPTS" || \
  sed -e 's/XXX_SNAPBALL_XXX/'"$SNAPBALL"'/g' < ../openssh-snapshot-basetemplate > "../$PT_BUILD_SCRIPTS"
chmod 0755 "../$PT_BUILD_SCRIPTS"

exec vagrant "$@"

# To retrieve the report:
# MACHINE=jessie
# vagrant ssh $MACHINE -- cat /tmp/openssh-output-log.txt > ~/ssh-reports/${MACHINE}.txt
