# We have a list of boxes, we assign IPs and port ranges by the list index
def private_network_ip(index)
  return "192.168.239." + (10 + index).to_s
end
def index_to_usable_port_range(index)
  base = 2300
  perbox = 20
  return ((base+perbox*index)..(base+perbox*(index+1)))
end

HOME_PROXY = 'http://192.168.120.21:3128/'

class PTMachine
  attr_reader :name, :box, :ostype,
    :vbmodifylist,
    :synctype, :syncargs, :typed_syncargs,
    :ssh_username, :env_additions
  @@copy_straight_attrs_vm = :base_mac, :boot_timeout, :box_version
  @@copy_straight_attrs_ssh = :shell, :sudo_command
  attr_reader *@@copy_straight_attrs_vm
  attr_reader *@@copy_straight_attrs_ssh

  def initialize(name, box, ostype)
    @name = name
    @box = box  # https://app.vagrantup.com/boxes/search
    @ostype = ostype
  end
  def with(var, value)
    self.instance_variable_set(var, value)
    return self
  end

  def mount_args()
    case @synctype
    when nil
      return {}
    when "disabled", "disable", "off", "no", "false", "0", 0
      return { disabled: true }
    end
    a = { type: @synctype }
    if @syncargs.nil? and (@typed_syncargs.nil? or not @typed_syncargs.has_key?(@synctype))
      # Here, our default options on a per-sync basis
      case @synctype
      when "nfs"
        a.merge!({nfs_udp: false})
      end
    else
      a.merge! @syncargs unless @syncargs.nil?
      a.merge! @typed_syncargs[@synctype] if (not @typed_syncargs.nil?) and @typed_syncargs.has_key?(@synctype)
    end
    return a
  end
end

# Most modern Vagrant images are defined with an embedded Vagrantfile, which
# sets a base_mac (from Packer); absence of this is an error even though back
# in 2014 mitchellh said they're not sure it's even needed any more.
#
# The initialize method takes the 3 most common attributes, use .with() to add
# anything else needed.
#
# MAC addresses are random, so far seen all 080027 OUI, even though that's
# "PCS Systemtechnik GmbH" per the IEEE registry (<http://standards-oui.ieee.org/oui.txt>).
# We stick to the pattern.
#
# Vagrant defaults to `bash -l` for the commands it runs itself (not `vagrant ssh`)
# so OSes which lack bash by default should override shell.

PTMACHINES = [
  # Project-maintained (I think) boxes
  PTMachine.new("jessie", "debian/jessie64", "debian-family").with(:@synctype, "nfs"),
  PTMachine.new("stretch", "debian/stretch64", "debian-family").with(:@synctype, "nfs"),  # vboxsf/etc removed, non-free
  PTMachine.new("trusty", "ubuntu/trusty64", "debian-family"),
  PTMachine.new("xenial", "ubuntu/xenial64", "debian-family").with(:@ssh_username, "ubuntu"),
  PTMachine.new("arch", "archlinux/archlinux", nil),
  PTMachine.new("netbsd7", "netbsd/NetBSD-7.0", nil),
  PTMachine.new("netbsd8", "NetBSD/NetBSD-8.0", nil),

  # Bento boxes maintained by Chef and officially supported by Hashicorp
  PTMachine.new("bento-centos7", "bento/centos-7", "rh-family"),
  PTMachine.new("bento-debian9.1", "bento/debian-9.1", "debian-family"),
  PTMachine.new("bento-fedora26", "bento/fedora-26", "rh-family"),
  PTMachine.new("bento-freebsd11", "bento/freebsd-11", nil).with(:@synctype, "disabled"),

  PTMachine.new("buster-daily", "fujimakishouten/debian-buster64", "debian-family")
    .with(:@synctype, "nfs")
    .with(:@env_additions, [
      ["PT_DISABLE_PTREPOS", "true"],
    ]),
    # fails on apt lock at initial start, on gnupg missing, on PT not having packages (known)

  PTMachine.new("laravel-homestead", "laravel/homestead", nil),
    # popular Ubuntu-derived dev image; already updated, do not add our stuff by default [might change]
    # Intended to be used with custom Vagrantfile setup, per ~/src/virtualization/laravel-homestead

  # FreeBSD: <https://forums.freebsd.org/threads/52717/>
  # They do package and OS update on boot, before SSH is available?
  # Note: at present time, sudo is segfaulting
  PTMachine.new("freebsd11.1", "freebsd/FreeBSD-11.1-STABLE", nil)
    .with(:@base_mac, "08002736F355").with(:@shell, "sh").with(:@synctype, "rsync")
    .with(:@vbmodifylist, [
      ["--memory", "1024"],
      ["--cpus", "1"],
      ["--hwvirtex", "on"],
      ["--audio", "none"],
      ["--nictype1", "virtio"],
      ["--nictype2", "virtio"],
    ]),

  PTMachine.new("slackware14.2", "crawford/slackware-14.2", nil),

  PTMachine.new("openbsd6.2", "SierraX/openbsd-6.2", nil)
    .with(:@box_version, "1.0.0")
    .with(:@sudo_command, "doas -n env %c")
    .with(:@synctype, "rsync")
    .with(:@syncargs, {
      rsync__rsync_path: "doas -n env rsync",
        }),
]

# Derived from https://gist.github.com/juanje/3797297
def local_cache_for_guest(basebox_name)
  # We did take a second parameter, 'venv', passed from node.vm.env but that
  # led to Vagrant errors, "The following settings shouldn't exist: env"; looks
  # like referencing it auto-vivifies it too early.
  if (/darwin/ =~ RUBY_PLATFORM) != nil
    cache_dir = Pathname.new(ENV['HOME']).join('Library', 'Caches', 'Vagrant')
  elsif ENV.has_key?('XDG_CACHE_HOME')
    cache_dir = Pathname.new(ENV['XDG_CACHE_HOME']).join('Vagrant')
  elsif File.exist?(File.join(ENV['HOME'], '.cache'))
    cache_dir = Pathname.new(ENV['HOME']).join('.cache', 'Vagrant')
  else
    cache_dir = Pathname.new(Vagrant::Environment.new.home_path).join('cache')
  end
  cache_dir = cache_dir.join('apt', basebox_name)
  partial_dir = cache_dir.join('partial')
  partial_dir.mkpath unless partial_dir.exist?
  cache_dir
end

def add_packaging_cache(ptb, node)
  if ptb.mount_args[:disabled]
    return false
  end
  case ptb.ostype
  when "debian-family"
    node.vm.synced_folder local_cache_for_guest(node.vm.box), "/var/cache/apt/archives/",
      typed_syncargs: { nfs: {
        bsd__nfs_options: ["mapall=#{Process.uid}"],
      } },
      **ptb.mount_args
  when "rh-family"
    node.vm.synced_folder local_cache_for_guest(node.vm.box), "/var/cache/yum/",
      typed_syncargs: { nfs: {
        bsd__nfs_options: ["mapall=#{Process.uid}"],
      } },
      **ptb.mount_args
  end
end

# https://stackoverflow.com/a/5471032/105927 by "mislav"
def which(cmd)
  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exts.each { |ext|
      exe = File.join(path, "#{cmd}#{ext}")
      return exe if File.executable?(exe) && !File.directory?(exe)
    }
  end
  return nil
end

Vagrant.configure(2) do |config|
  PTMACHINES.each_with_index do |ptb, machine_index|
    # NB: Synced folders are done before provision scripts, independent of order defined here.

    config.vm.define ptb.name, autostart: false do |node|
      node.vm.box = ptb.box
      provision_env = {}

      PTMachine.class_variable_get(:@@copy_straight_attrs_vm).each { |attr|
        atattr = '@' + attr.to_s
        if ptb.instance_variable_defined?(atattr)
          node.vm.instance_variable_set(atattr, ptb.instance_variable_get(atattr))
        end
      }
      PTMachine.class_variable_get(:@@copy_straight_attrs_ssh).each { |attr|
        atattr = '@' + attr.to_s
        if ptb.instance_variable_defined?(atattr)
          node.ssh.instance_variable_set(atattr, ptb.instance_variable_get(atattr))
        end
      }

      unless ptb.vbmodifylist.nil?
        node.vm.provider :virtualbox do |vb|
          ptb.vbmodifylist.each do |item, value|
            vb.customize ["modifyvm", :id, item, value]
          end
        end
      end

      node.vm.network "private_network", ip: private_network_ip(machine_index)
      node.vm.usable_port_range = index_to_usable_port_range(machine_index)

      if which("not_at_home").nil?
        node.vm.provision "shell", inline: "touch /tmp/home-status-unknown", name: "To be home or not to be home"
      elsif system("not_at_home")
        node.vm.provision "shell", inline: "touch /tmp/am_not_at_home", name: "Not At Home"
      else
        node.vm.provision "shell", inline: "touch /tmp/am_at_home", name: "At Home"
        provision_env['http_proxy'] = HOME_PROXY
      end
      # HTTP proxy in _our_ environment takes precendence over any home HTTP proxy, pass that in env
      # Note that the ptlocal setup uses an apt-cacher-ng setup and that remains, if at home
      provision_env['http_proxy'] = ENV['http_proxy'] if ENV.has_key?('http_proxy')

      node.vm.synced_folder ".", "/vagrant", **ptb.mount_args
      add_packaging_cache(ptb, node)
      # my Ruby/Vagrant knowledge is too weak to get this in a usable form from node.ssh.username
      # (I just see an anonymous Object)
      unless ptb.ssh_username.nil?
        provision_env['PT_VAGRANT_USER'] = ptb.ssh_username
      end

      unless ptb.env_additions.nil?
        ptb.env_additions.each do |envkey, envval|
          provision_env[envkey] = envval
        end
      end

      unless ptb.ostype.nil?
        ptlocal = Pathname.new(ENV['HOME']).join('etc', 'vagrant', "ptlocal.#{ptb.ostype}.sh")
        node.vm.provision "shell", path: ptlocal.to_s, env: provision_env, name: "pennocktech-local" if ptlocal.exist?
      end

      if Pathname.new(ENV['HOME']).join('.personal', 'reduced').exist?
        %w(.vimrc .zshrc).each do |fn|
          node.vm.provision "file", source: "~/.personal/reduced/#{fn}", destination: fn
        end
      end

      ENV.fetch('PT_BUILD_ASSETS', '').split.each do |asset|
        node.vm.provision "file", source: asset, destination: "/tmp/" + Pathname.new(asset).basename.to_s
      end

      ENV.fetch('PT_BUILD_SCRIPTS', '').split.each do |script|
        node.vm.provision "shell",
          path: "#{ENV['HOME']}/etc/vagrant/#{script}",
          env: provision_env,
          name: "build-#{script}"
      end

    end # config.vm.define using node as iteration variable
  end # PTMACHINES iteration
end # Vagrant configure
