#!/bin/sh -eux

# Filled in when template converted:
tarball='/tmp/XXX_SNAPBALL_XXX'
id

if [ -d /etc/apt ]; then
	(
	export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
	apt-get -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" build-dep openssh
	)
elif [ -f /etc/yum.conf ] || [ -d /etc/yum ]; then
	(
	yum -y install yum-utils
	yum -y groupinstall 'Development Tools'
	yum-builddep -y openssh
	)
elif [ -f /etc/pacman.conf ]; then
	(
	pacman --noconfirm -Sy base-devel
	)
fi

# netbsd doesn't support -v:
mkdir -p /var/empty

sudo -Hiu "${PT_VAGRANT_USER:-vagrant}" <<EOSCRIPT
set -x
cd
tar zxf $tarball
cd openssh
( ./configure && make tests ) >/tmp/openssh-output-log.txt 2>&1
EOSCRIPT
